### ISSUE TITLE
Type-error - '<' not supported between instances of 'NoneType' and 'str'

### ISSUE THREAD

**Issue by ghost** [TimEnglart/BlackBoard-Course-Downloader#12]
Installation [✓]
Running python main.py [✓]
Entering username [✓]
Entering password [✓]

Error appears a few seconds after the console clears with the username at the top of the page

```
Traceback (most recent call last):
  File "main.py", line 308, in <module>
    handle_arguments()
  File "main.py", line 118, in handle_arguments
    return main(args)
  File "main.py", line 143, in main
    navigate(client)
  File "main.py", line 169, in navigate
    next_item = navigation(
  File "main.py", line 263, in navigation
    options = sorted(
TypeError: '<' not supported between instances of 'NoneType' and 'str'
```

I have run the debug.py script however the following error message also appeared, the json still created so here it is in a zip format 

[dump.zip](https://github.com/TimEnglart/BlackBoard-Course-Downloader/files/5145188/dump.zip)

```
Traceback (most recent call last):
  File "debug.py", line 86, in <module>
    test()
  File "debug.py", line 82, in test
    json.dump(dumps, file)
  File "C:\Program Files (x86)\Python38-32\lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Program Files (x86)\Python38-32\lib\json\encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "C:\Program Files (x86)\Python38-32\lib\json\encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "C:\Program Files (x86)\Python38-32\lib\json\encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "C:\Program Files (x86)\Python38-32\lib\json\encoder.py", line 438, in _iterencode
    o = _default(o)
  File "C:\Program Files (x86)\Python38-32\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DownloadQueue is not JSON serializable
```

**Comment by ghost** [comment]
Update - adding the mass download flag (-m) bypasses this issue, however it would be nice to still have the choice to pick certain courses

**Comment by TimEnglart** [comment]
It seems that when it is trying to order the course names it is coming across a None value. I have pushed an update that should hopefully resolve the issue.
