### ISSUE TITLE
Login Issues

### ISSUE THREAD

**Issue by TimEnglart** [TimEnglart/BlackBoard-Course-Downloader#19]
Please comment here if you experience any login issues with program.

### Tested Login Methods:
- **Institute Local**: Use username and password login method (cookie login doesn't cause errors).
- **Microsoft + MFA**: Use cookie login w/ username (remove @institution.com if your username is an email).

Please use the response template here so that necessary details are provided (feel free to add extra fields where appropriate): 

```
Login Credential Type: (Institute, Microsoft, Google, etc)
Login Method: (Username + Password, Cookies)
Notes: (Fill with what you were going to comment)
```

**Comment by willywaggler** [comment]
Login Credential Type: Institute
Login Method: Username + Password
Notes:
Hi Tim,
I'm having trouble logging in. I have absolutely no understanding of Python so it could be a stupid mistake on my part; apologies if so.
I first enter my username and password. Then I press c and search 'Trinity', and press 1.
I then get the following error:
```
FAILED TO LOGIN
Username: [my username]
Learn Site: https://tcd.blackboard.com
Response Status Code: 200
Response Body: <?xml version="1.0" encoding="UTF-8"?>
<mobileresponse status="LOGIN_FAILED"><![CDATA[Unable to login user]]></mobileresponse>


[Enter 'r' to Retry]
```
This tool looks like an absolutely fantastic time-saver so I hope I can get it working!

**Comment by TimEnglart** [comment]
Hi @willywaggler,

Sorry to see that you can't login. You seem to be doing everything alright on your part and the server seems to be working; so all I can recommend is trying out the `--browser` flag accompanied by your browser your already logged in with ( eg. `--browser 'chrome'`) and trying to login again and/or playing around with your `username` input (using username, email, first part of email etc.) and verifying your `password` input.

Hopefully you figure it out and feel free to reply if there are any other issues.

**Comment by willywaggler** [comment]
Hi @TimEnglart,

Thanks for your help, but I still don't seem to be getting anywhere. Adding `--browser 'chrome'` changes the error message to:
```
Attempting to Grab Cookies for "tcd.blackboard.com" from browser: chrome
FAILED TO LOGIN
Username: [my username]
Learn Site: https://tcd.blackboard.com
Response Status Code: 200
Response Body: <?xml version="1.0" encoding="UTF-8"?>
<mobileresponse status="LOGIN_FAILED"><![CDATA[Unable to login user]]></mobileresponse>


[Enter 'r' to Retry]Grabbed Cookies for "tcd.blackboard.com" from browser: chrome
````
I used my email as well, but that didn't help (first part of email and username are the same). I also entered my password as `--password '[my password]'` to make sure that I wasn't entering it incorrectly when it's not visible, but still no luck.

**Comment by poketch** [comment]
Hi @TimEnglart,

I'm experiencing the same problem as the above user.

Login Credential Type: Institute
Login Method: both username+password and cookies
Notes:
Your program got shared in my class discord a few days ago and one of my classmates said they used it with great effect.
I tried using it without the -B option and failed to login, then used `--browser edge` and failed again. Contacted my classmate and they said they'd used firefox so I tried both firefox and chrome with no luck (I was logged into blackboard on all three prior to attempting). See below for an example of the screen dump 

```
C:\Users\mpalmerkeizer\Downloads\BlackBoard-Course-Downloader-master>python main
.py -B edge
Loading Configuration File: C:\Users\mpalmerkeizer\Downloads\BlackBoard-Course-D
ownloader-master\config.json
Saving Content To: C:\Users\mpalmerkeizer\Downloads\BlackBoard-Course-Downloader
-master

** MAKE SURE YOU ARE AUTHENTICATED IN YOUR BROWSER BEFORE PROCEEDING **
You have enabled the --browser argument. This will use your blackboard sites coo
kies from your chosen browser: edge.
If you use an email address to login enter your username for the email when prom
pted for a username.
e.g. Your normal login is: "me@example.com", use "me" as your username

Enter Username []: mbcxajp4
Enter Password:
Enter Black Board Host Website [ or 'c' to Search]: c
Institute Name: manchester
[1] University of Manchester
Enter  Number to Select ['c' to Exit]:
1
Attempting to Grab Cookies for "online.manchester.ac.uk" from browser: edge
Grabbed Cookies for "online.manchester.ac.uk" from browser: edge
FAILED TO LOGIN
Username: mbcxajp4
Learn Site: https://online.manchester.ac.uk
Response Status Code: 200
Response Body: <?xml version="1.0" encoding="UTF-8"?>
<mobileresponse status="LOGIN_FAILED"><![CDATA[Unable to login user]]></mobilere
sponse>


[Enter 'r' to Retry]
```
some additional notes: 
I've tried this on two different windows systems and on one of them used Ubuntu20.04 through WSL2 to try through Linux none of these worked.
The screen dump claims to load from config.json which is not a file that exists in any of my directories. Is this intended behaviour?
Also typing the host website directly instead of using search does not assign a value to `args.institute` resulting in a crash. This is an unrelated bug I noticed when testing different methods
See my dump.json file below if that is of use in diagnosing the problem
[dump.txt](https://github.com/TimEnglart/BlackBoard-Course-Downloader/files/6971850/debug.txt)

**Comment by TimEnglart** [comment]
@poketch, Thanks for giving me some more information. I don't know whether this affects you guys but the current implementation of cookies can produce some irregular errors that cause failed login error which were not caught by me when I was using the application. I'll be pushing a commit that hopefully fixes that issue by the weekend. 

> The screen dump claims to load from `config.json `which is not a file that exists in any of my directories. Is this intended behaviour?

Yeah, that was intended just so you knew where your config would be located once generated, which is after you successfully log in. Good catch on that definitely would be confusing when you are trying to diagnose issues.

> Also typing the host website directly instead of using search does not assign a value to `args.institute` resulting in a crash. This is an unrelated bug I noticed when testing different methods

Thanks for the heads up, I fix that up in the commit I mentioned above :)

Hopefully this will fix your issues. But that nature of these things is that there isn't much diagnosing we can do to know exactly what the issue is when I come to the authentication. Probably need to invest in tests so I dont break more thing ;)

**Comment by willywaggler** [comment]
Hi @TimEnglart, I've downloaded the updated version but it still gives the same error message as before.

**Comment by josh0-jrg** [comment]
@TimEnglart  I get the same error as @poketch. I tried using the cookies login and this is the message I get (I am alos trying to get onto the University of Manchester blackboard!)


```
`>python3 main.py -m -l "../../" -r -B Firefox
Loading Configuration File: path\config.json
Saving Content To: path\4th year course material\Downloading materials

** MAKE SURE YOU ARE AUTHENTICATED IN YOUR BROWSER BEFORE PROCEEDING **
You have enabled the --browser argument. This will use your blackboard sites cookies from your chosen browser: Firefox.
If you use an email address to login enter your username for the email when prompted for a username.
e.g. Your normal login is: "me@example.com", use "me" as your username

Enter Username []: ------
Enter Password:
Enter Black Board Host Website [ or 'c' to Search]: c
Institute Name: manchester
[1] University of Manchester
Enter  Number to Select ['c' to Exit]:
1
Attempting to Grab Cookies for "online.manchester.ac.uk" from browser: firefox
Traceback (most recent call last):
  File "path\BlackBoard-Course-Downloader-master\main.py", line 370, in <module>
    handle_arguments()
  File "path\BlackBoard-Course-Downloader-master\main.py", line 138, in handle_arguments
    return main(args)
  File "path\BlackBoard-Course-Downloader-master\main.py", line 154, in main
    login_resp = client.login()
  File "path\BlackBoard-Course-Downloader-master\blackboard.py", line 171, in login
    self.user_id = response_xml['@userid']
KeyError: '@userid'
Grabbed Cookies for "online.manchester.ac.uk" from browser: firefox`
```

I also tried some other browsers but they didn't work either (Edge and Chrome) to find the same error as @poketch 

```
`Enter Black Board Host Website [ or 'c' to Search]: c
Institute Name: manchester
[1] University of Manchester
Enter  Number to Select ['c' to Exit]:
1
Attempting to Grab Cookies for "online.manchester.ac.uk" from browser: chrome
FAILED TO LOGIN
Username: ------
Learn Site: https://online.manchester.ac.uk
Response Status Code: 200
Response Body: <?xml version="1.0" encoding="UTF-8"?>
<mobileresponse status="LOGIN_FAILED"><![CDATA[Unable to login user]]></mobileresponse>


[Enter 'r' to Retry]Grabbed Cookies for "online.manchester.ac.uk" from browser: chrome
^Z
Traceback (most recent call last):
  File "path\BlackBoard-Course-Downloader-master\main.py", line 370, in <module>
    handle_arguments()
  File "path\BlackBoard-Course-Downloader-master\main.py", line 138, in handle_arguments
    return main(args)
  File "path\BlackBoard-Course-Downloader-master\main.py", line 179, in main
    if input("FAILED TO LOGIN\n" +
EOFError`

```

I just replaced file directory paths with "path".

**Comment by poketch** [comment]
Hi @TimEnglart, 
The new commit unfortunately didn't work for me either but I tried the other branch that's available and it seems to be working as intended with scraping cookies from Firefox browser, 
so maybe something in the cookie implementation used back then has changed and is causing the issue we all seem to be facing.
Anyway, Thanks for making this great program.

**Comment by jfrancisg2** [comment]
Hi @poketch,
Did you manage to get the web scrape working with firefox? I'm not sure how to proceed after:
```
Enter Username []: --------
[1] Username & Password
[2] Browser Cookies
Enter How would you like to login Number to Select ['c' to Exit]:
2
Enter Black Board Host Website [ or 'c' to Search]: c
Institute Name: Manchester
[1] University of Manchester
Enter  Number to Select ['c' to Exit]:
1
online.manchester.ac.uk
[1] Chrome
[2] Firefox
[3] Edge
[4] Opera
[5] Chromium
[6] Unknown
Enter Select a Browser to Pull Your Cookies from Number to Select ['c' to Exit]:
2
Attempting to Grab Cookies from: Firefox

Cookies:
[(bunch of cookies)]Grabbed Cookies from: Firefox
```

**Comment by ManishBhat** [comment]
I have the same issue as @poketch and @willywaggler.

**Comment by kafkaluise** [comment]
Login Credential Type: Institute
Login Method: Username + Password, Cookies
Notes: 

Hi Tim,

i tried your using your script for Freie Universität Berlin but somehow I can't login. I've already tried to login with email, username etc. Using the browser option also doesn't help. Is there anything else I can try?

```
Enter Username []: starogaa98
Enter Password:
Enter Black Board Host Website [ or 'c' to Search]: c
Institute Name: Berlin
[1] Freie Universitaet Berlin
Enter  Number to Select ['c' to Exit]:
1
FAILED TO LOGIN
Username: starogaa98
Learn Site: https://lms.fu-berlin.de
Response Status Code: 200
Response Body: <?xml version="1.0" encoding="UTF-8"?>
<mobileresponse status="LOGIN_FAILED"><![CDATA[Unable to login user]]></mobileresponse>
```
