### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by fn5** [TimEnglart/BlackBoard-Course-Downloader#7]
Hello, thankyou for making this script.
I'm trying to use it, and I am finding my institution through the search and selecting it. After this, I get the following:

`
Traceback (most recent call last):
  File "main.py", line 276, in <module>
    handle_arguments()
  File "main.py", line 101, in handle_arguments
    return main(args)
  File "main.py", line 123, in main
    navigate(bbc)
  File "main.py", line 147, in navigate
    next_item = navigation(options=selected_item.courses(), attribute='name', sort=True, title='Course')
  File "/mnt/mpathy/toastpaint/UQ/BlackBoard-Course-Downloader/blackboard.py", line 114, in courses
    course_data = self.session.get(self.site + endpoint).json()
  File "/usr/lib64/python3.6/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/toastpaint/virtualenv3/lib/python3.6/site-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/home/toastpaint/virtualenv3/lib/python3.6/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/home/toastpaint/virtualenv3/lib/python3.6/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
`

**Comment by TimEnglart** [comment]
Hi @jackitsdotcom. Sorry that your experiencing this issue. It looks like it is caused by a JSON parsing failure when it fetches your courses. If you are able to would you be able to run the `debug.py` script and upload the generated `dump.json` file in a `zip` format. So we can identify more specific details.

**Comment by fn5** [comment]
Hi Tim! Thankyou for the reply. 
Unfortunately when I run debug.py it does not generate a dump.json file. Do I need to run it with any flags?

```
Enter Username [s4596946]:

Enter Password:

Enter Black Board Host Website [https://learn.uq.edu.au or 'c' to Search]:

Traceback (most recent call last):
  File "debug.py", line 86, in <module>
    test()
  File "debug.py", line 74, in test
    get_courses()
  File "debug.py", line 56, in get_courses
    courses = request.json()
  File "/usr/lib64/python3.6/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/toastpaint/virtualenv3/lib/python3.6/site-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/home/toastpaint/virtualenv3/lib/python3.6/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/home/toastpaint/virtualenv3/lib/python3.6/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
Happy to provide you with the details for your own attempts but I'd have to email them to you.
Cheers.

**Comment by TimEnglart** [comment]
Damn. The only other thing I can offer you to do is log into your institutes blackboard then use this link `https://learn.uq.edu.au/learn/api/public/v1/users/userName:s4596946/courses` and describe the response or post it back. Because it looks like it isn't returning a JSON response.

Once again sorry that you are having these issues.

**Comment by fn5** [comment]
Looks like they have blocked /public/ on the serverside.
Once I try https://learn.uq.edu.au/learn/api/v1/users/?userName=s4596946, I manage to get something interesting. Because I know the full course code I can also see if I go here https://learn.uq.edu.au/learn/api/v1/courses/?courseId=ABTS3020S_6960_60698 I also get specific course info but nothing like if I run it at my other login with QUT which works fine...

Kudos for them for locking it down, but a real shame. If I have time after November 15 I might have a deeper look...
Cheers, Jack

**Comment by TimEnglart** [comment]
Nice Catch. I'd also be more than happy to look into it more in a couple of weeks.

**Comment by ad-e** [comment]
I'm at UQ too and met the same issue. Did you ever look into this further?

**Comment by TimEnglart** [comment]
I did end up having a look and it seems that removing the /public/ endpoint results in the same endpoint accessed by the learn website itself (at least for my uni). The issue I ran into was that the returned response had a different layout between the endpoints and the internal API isn't publicly documented from what I could find which requires me to track requests to get the responses and queries required to achieve the same results on the /public/ API. But it isn't something I am planning on implementing within this project for the time being.
